### ISSUE TITLE
getLocalIP() returns empty string after connecting to AP

### ISSUE THREAD

**Issue by zenAudio** [itead/ITEADLIB_Arduino_WeeESP8266#1]
The following code:

```
 auto str = wifi.getJoinedDeviceIP();
 cout.print("wifi.getJoinedDeviceIP() = ");
 cout.println(str);
```

returns "" even after connecting to an AP. This code was inserted into the example code, and all the other "debug" print statements look correct (i.e. I'm sure I'm connecting to AP and setting up server correctly).

**Comment by shennongmin** [comment]
Maybe you use the wrong API:
String  getJoinedDeviceIP (void) : Get the IP list of devices connected to SoftAP. 
String  getLocalIP (void) : Get the IP address of ESP8266.
