### ISSUE TITLE
[changed] AT+CIPMODE

### ISSUE THREAD

**Issue by 0crash0** [itead/ITEADLIB_Arduino_WeeESP8266#10]
Hello,
exist some possibility to change baud rate for hardware serial and software serial from main sketch?

or i must change it in ESP8266.h ?? 

and if not exist can you modify lib  for doing that

**Comment by 0crash0** [comment]
i'm so stupid ... 
i'll understand how do that:
ESP8266 wifi(Serial1,115200);

**Comment by 0crash0** [comment]
FW Version:AT version:0.21.0.0
i've error while trying to run tcp server
because  your lib not support AT+CIPMODE

**Comment by shennongmin** [comment]
I'am sorry! baud rate cannot be changed for now due to the version of esp8266 firmware.
