### ISSUE TITLE
Problems using SoftwareSerial as ESP8299 port

### ISSUE THREAD

**Issue by Luminaric** [itead/ITEADLIB_Arduino_WeeESP8266#12]
I'm running the example TCPClientSingleUNO it's straight forward, however when I complile with only the #defines needed to connect changed I get this.
TCPClientSingleUNO.ino:30:22: error: no matching function for call to 'ESP8266::ESP8266(SoftwareSerial&)'
ESP8266.h defines this.  Any ideas where the problem my lay?

**Comment by shennongmin** [comment]
In README.md, I have mentioned it. 
Please read the section "Using SoftwareSerial" in README.md.
