### ISSUE TITLE
Binary data is not return correctly if contains 0x00

### ISSUE THREAD

**Issue by tomhampshire** [itead/ITEADLIB_Arduino_WeeESP8266#13]
The following line in uint32_t ESP8266::recvPkg(uint8_t *buffer, uint32_t buffer_size, uint32_t *data_len, uint32_t timeout, uint8_t *coming_mux_id)

memcpy(buffer, 
data.substring(index_colon + 1, index_colon + 1 + len).c_str(), 
ret);

(around line 367 of ESP8266.cpp)

Returns incomplete data if a 0x00 occurs in 'data' as this is interpreted as '\0' and terminates the string. I have made a hacky solution by buffering all incoming data in a char array 'charData', and replacing the above with the following:

memcpy(buffer, &charData[index_colon + 1], ret);

I would advise using a statically assigned char array as a global buffer for all of your functions, rather than using the arduino String object, as the dynamic memory allocation is slow and may cause problems.

**Comment by shennongmin** [comment]
Thanks for your advice and your attention!
Good one! We will upgrade ESP8266::recvPkg method as soon as possible.
