### ISSUE TITLE
JoinAP

### ISSUE THREAD

**Issue by SBKila** [itead/ITEADLIB_Arduino_WeeESP8266#15]
Hi,

My ESP8266 firmware is
AT+GMR

AT version:0.21.0.0
SDK version:0.9.5

OK

My arduino is a leonardo R3

I have used for the first time your library this weekend. I was not able to use your example ConnectWifi.
I have update the example with my SSID and password. and also ESP8266 object creation as follow
ESP8266 wifi(Serial1,115200);

the log I get is something like this:

setup begin
FW Version:0.21.0.0
to station ok
Join AP failure
setup end

In my first test application of the ESP8266 I was doing as follow and it able to join the SSID
String cmd="AT+CWMODE=1";
Serial.print("SEND: ");
Serial.println(cmd);
Serial1.println(cmd);
Serial1.flush();
delay(2000);
cmd="AT+CWJAP=\"";
cmd+=ssid;
cmd+="\",\"";
cmd+=pwd;
cmd+="\"";
Serial.print("SEND: ");
Serial.println(cmd);
Serial1.println(cmd);
Serial1.flush();
delay(5000);
return Serial1.find("OK");

I have a look to your .CPP file, and you are doing quite the same but I was not able to connect my WIFI.

I test I have updated you .CPP file as follow, 

bool ESP8266::joinAP(String ssid, String pwd)
{

```
//sATCWMODE(1);
delay(2000);
String cmd="AT+CWMODE=1";
```

  Serial.print("SEND: ");
  Serial.println(cmd);
  m_puart->println(cmd);
  m_puart->flush();
  delay(2000);
  cmd="AT+CWJAP=\"";
  cmd+=ssid;
  cmd+="\",\"";
  cmd+=pwd;
  cmd+="\"";
  Serial.print("SEND: ");
  Serial.println(cmd);
  m_puart->println(cmd);
  m_puart->flush();
  delay(5000);
  return m_puart->find("OK");

}

and this time i was able to connect my WIFI.

any clue for me?

Regards

I have also try without success:
modifying 
bool ESP8266::sATCWJAP 
bool ESP8266::sATCWJAP(String ssid, String pwd)
{
    String data;
    rx_empty();
    m_puart->print("AT+CWJAP=\"");
    Serial.print("AT+CWJAP=\"");

```
m_puart->print(ssid);
Serial.print(ssid);

m_puart->print("\",\"");
Serial.print("\",\"");

m_puart->print(pwd);
Serial.print(pwd);

m_puart->println("\"");
Serial.println("\"");

delay(5000);
return m_puart->find("OK");
```

/*
    data = recvString("OK", "FAIL", 10000);
    if (data.indexOf("OK") != -1) {
        return true;
    }
    return false;
*/
}

the output was AT+CWJAP="MYSSID","MYPASSWORD"

**Comment by cszp17** [comment]
We have been in the new version to repair the fix the problem,you can have a try.Thanks!
