### ISSUE TITLE
extra \r in eATGMR

### ISSUE THREAD

**Issue by zenmanenergy** [itead/ITEADLIB_Arduino_WeeESP8266#17]
In bool ESP8266::eATGMR I think there is an extra \r at least with my version of the esp8266 (0020000903 compiled @ Dec 15 2014 19:43:31 AITHINKER-20141206)

change:
return recvFindAndFilter("OK", "\r\r\n", "\r\n\r\nOK", version);

to:
return recvFindAndFilter("OK", "\r\n", "\r\n\r\nOK", version);

**Comment by freezingzz** [comment]
will fix this in next version update , and new version will support more AT commands

**Comment by cszp17** [comment]
You can use our way to try to see if there is no problem.Then can check the serial port using hex printed characters, you will find that is \ r \ r \ n.Thank you for your questions.
