### ISSUE TITLE
returning empty string

### ISSUE THREAD

**Issue by zenmanenergy** [itead/ITEADLIB_Arduino_WeeESP8266#18]
In bool ESP8266::recvFindAndFilter

at the end it has:

data = "";
return false;

If those two if statements are never satisfied it returns an empty string which shouldn't happen, but when it does it appears like the library isn't working, when it's just a minor bug. I think instead it should be:

data = data_tmp;
return false;

That way if the filter doesn't work, it'll just return the full string.

**Comment by cszp17** [comment]
Thank you for your question.we will fix this in new version!
