### ISSUE TITLE
Configurable Baud rate is not supported

### ISSUE THREAD

**Issue by Bigguy34** [itead/ITEADLIB_Arduino_WeeESP8266#2]
Currently the baud rate is hardcoded to be 9600, it would be nice to make this a setting so that users who use the library could set the baud rate.

**Comment by Bigguy34** [comment]
I was going to submit a pr for this I just haven't had any time. Awesome library by the way!

**Comment by shennongmin** [comment]
The baud rate for communication between mainboard and ESP8266 is defined by AT firmware not our code. At current, it is 9600.
