### ISSUE TITLE
extra \r in eATCWLAP

### ISSUE THREAD

**Issue by zenmanenergy** [itead/ITEADLIB_Arduino_WeeESP8266#20]
bool ESP8266::eATCWLAP

extra \r

change:

return recvFindAndFilter("OK", "\r\r\n", "\r\n\r\nOK", list, 10000);
to:

return recvFindAndFilter("OK", "\r\n", "\r\n\r\nOK", list, 10000);

**Comment by cszp17** [comment]
You can use our way to try to see if there is no problem.Then can check the serial port using hex printed characters, you will find that is \ r \ r \ n.Thank you for your questions.

**Comment by cszp17** [comment]
You can use our way to try to see if there is no problem.Then can check the serial port using hex printed characters, you will find that is \ r \ r \ n.Thank you for your questions.
