### ISSUE TITLE
extra \r in eATCIFSR

### ISSUE THREAD

**Issue by zenmanenergy** [itead/ITEADLIB_Arduino_WeeESP8266#21]
Extra \r in eATCIFSR

change
return recvFindAndFilter("OK", "\r\r\n", "\r\n\r\nOK", list);

to:
return recvFindAndFilter("OK", "\r\n", "\r\n\r\nOK", list);

**Comment by cszp17** [comment]
You can use our way to try to see if there is no problem.Then can check the serial port using hex printed characters, you will find that is \ r \ r \ n.Thank you for your questions.
