### ISSUE TITLE
String objects stop responding to appends in recvString

### ISSUE THREAD

**Issue by julianh2o** [itead/ITEADLIB_Arduino_WeeESP8266#26]
I'm using an atmega32u4 board and working with this library.. Sometimes things seem to work pretty well, but every other reset or so.. wifi.getIpStatus() was returning a blank string. I added some debugging to the recvString method and it is clearly reading the correct data from the ESP (by printing out the characters as they arrive). However, the string append seems to be failing (probably due to memory issues). Printing the length of the string after the "data += a" line is always returning 0.

Do you have any suggestions for how I might use this library and avoid this issue? I've started refactoring the library to use cstrings instead of Arduino StringObjects in the hopes that it'll fix this and cause the library to use significantly less memory. I'll provide a fork and pull request if/when I finish this refactoring.

**Comment by cszp17** [comment]
To reset the problem of what you say, I will go to a test. However, getIpStatus (API) that is running on my MEGA2560 board, there is no problem in the "data+=a" behind the print the string length
