### ISSUE TITLE
Pinout

### ISSUE THREAD

**Issue by wifixcort** [itead/ITEADLIB_Arduino_WeeESP8266#3]
It would be good to include the pinout in the readme

**Comment by Phyks** [comment]
:+1: It was part of the [old lib](https://github.com/itead/ITEADLIB_Arduino_ESP8266) and it was way much easier to start with these chips using the old lib :)

**Comment by wifixcort** [comment]
I thought the same, but if someone does not know the old library and starts
with the new library, could immediately discard it for not knowing the
pinout.

It's just a suggestion :)

2015-02-24 15:50 GMT-06:00 Lucas Verney notifications@github.com:

**Comment by prc7965** [comment]
But i like the way with old lib. It supports more boards & u can just leave
the RTX jumpers when uploading code.
Hmm, maybe i'm misunderstanding that?
Sorry 4 my bloody poor English, i learned from my gym teacher. LOL

On Wed, Feb 25, 2015 at 12:20 PM, wifixcort notifications@github.com
wrote:

> I thought the same, but if someone does not know the old library and starts
> with the new library, could immediately discard it for not knowing the
> pinout.
> 
> It's just a suggestion :)
> 
> 2015-02-24 15:50 GMT-06:00 Lucas Verney notifications@github.com:
> 
> > [image: :+1:] It was part of the old lib
> > https://github.com/itead/ITEADLIB_Arduino_ESP8266 and it was way much
> > easier to start with these chips using the old lib :)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/itead/ITEADLIB_Arduino_WeeESP8266/issues/3#issuecomment-75854183
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/itead/ITEADLIB_Arduino_WeeESP8266/issues/3#issuecomment-75903279
> .

## 

神秘阿當
董嘉旭

北京嘉娛世紀網絡科技有限公司
http://www.jysj.com

**Comment by shennongmin** [comment]
Thanks for attentions from wifixcort, Phyks and prc7965!
We have add pinout in readme for default examples. If you need to specify another serial for communication with ESP8266, modifying the code and the hardware connection are so easy.
