### ISSUE TITLE
MQTT & REST support

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [itead/ITEADLIB_Arduino_WeeESP8266#30]
Are you planning to add MQTT and REST support to your awesome library?
This would be enormous for IoT projects.
I do not want to run the ESP8266 as standalone - because of some other reasons.
But there is no solution out there to have a ESP8266 connected to Arduino or Teensy
and use MQTT library directly on your Arduino / Teensy.

**Comment by cszp17** [comment]
We will consider it, thank you for your attention!

**Comment by tobiasschaber** [comment]
I would really appreciate to see that coming, too!
