### ISSUE TITLE
Flashing version 0.22 AT firmware

### ISSUE THREAD

**Issue by terrag42** [itead/ITEADLIB_Arduino_WeeESP8266#34]
Hello, 
I am having trouble getting my esp8266 to communicate via UART with my Arduino Mega.
I downloaded the SDK version 1.0.0 with AT firmware version 0.22 from the
[espressif website](http://bbs.espressif.com/viewtopic.php?f=46&t=286)
Here are the files I flashed using the NodeMCU flasher program for Windows:
boot_v1.2.bin at 0x00000
user1.512.new.bin at 0x01000
blank.bin at 0x7E000

Are these files the correct ones, with the correct offsets?

Is there a way to ensure that I have the correct firmware installed before running the "test" example?
Thank you.

**Comment by cszp17** [comment]
Have you set the macro to #define  USER_SEL_VERSION         VERSION_22 ?
