### ISSUE TITLE
UDP 

### ISSUE THREAD

**Issue by Smart-Dragon** [itead/ITEADLIB_Arduino_WeeESP8266#35]
Help me, please!
Code in standart WiFi Arduino module for UDP:

void setup() {
   ...
   Udp.begin(localPort);
}
void loop() {

  // if there's data available, read a packet
  int packetSize = Udp.parsePacket();
  if (packetSize){ ... }

}

How to use your library to listen UDP packets to a specific port?

**Comment by a-andreyev** [comment]
first of all you should specify what's the version of the firmware flashed on you esp8266 module

**Comment by Smart-Dragon** [comment]
FW Version:AT version:0.25.0.0(Jun  5 2015 16:27:16)
SDK version:1.1.1
Ai-Thinker Technology Co. Ltd.
Jun  5 2015 23:07:20

**Comment by a-andreyev** [comment]
I would recommend to try my fork #32 for the AT commands version higher than v0.22 for apropriate UDP support (https://github.com/semiotproject/ITEADLIB_Arduino_WeeESP8266)
You could try something like in the .../examples/.../UDPClientSingle.ino with this implementation to get UDP server working.
Good luck :)

**Comment by Smart-Dragon** [comment]
Everything works! Thanks!
