### ISSUE TITLE
Serial1' was not declared in this scope

### ISSUE THREAD

**Issue by teinhonglo** [itead/ITEADLIB_Arduino_WeeESP8266#36]
Sorry I have two question

(1).I run the sample code  "Connect Wifi", but complier error "Serial1' was not declared in this scope".

(2).The circuit isn't it?
http://microcontrollerelectronics.com/wp-content/uploads/2014/12/esp8266_bb.png

**Comment by a-andreyev** [comment]
Scheme is ok in general, but I'm not sure you could easily use Leonardo Serial1 for communication:

> The Arduino Leonardo board uses Serial1 to communicate via TTL (5V) serial on pins 0 (RX) and 1 (TX). Serial is reserved for USB CDC communication.

As an option, try to test it with SoftwareSerial

**Comment by teinhonglo** [comment]
sorry i link png is wrong, i use arduino uno, as below
http://rancidbacon.com/images/project/esp8266-doc/ESP8266-Connections_bb-fixed-small.png

i just include library(ITEADLIB_Arduino_WeeESP8266-master.zip) ,open example and compiler "Connect Wifi" , then output is
http://i.imgur.com/4DSaKRe.jpg

---

Oops, i look for it !! sorry...
#include "ESP8266.h"
#include <SoftwareSerial.h>

SoftwareSerial mySerial(3, 2); /\* RX:D3, TX:D2 */
ESP8266 wifi(mySerial);

in this way , the circuit is correct?

**Comment by a-andreyev** [comment]
Arduino Uno doesn't have Serial1, only Serial:

> Serial: 0 (RX) and 1 (TX). Used to receive (RX) and transmit (TX) TTL serial data. These pins are connected to the corresponding pins of the ATmega8U2 USB-to-TTL Serial chip.

If you are going to use Software Serial as described:

```
#include "ESP8266.h"
#include <SoftwareSerial.h>

SoftwareSerial mySerial(3, 2); // uno sw RX(pin3) --> esp8266 TX, uno sw TX(pin2) --> esp8266 RX
ESP8266 wifi(mySerial);
```

You should connect pins 3 and 2 (software rx and tx) to esp8266 tx and rx pins (in reverse mode: rx to tx) according to pinout:
![Screenshot](http://www.autonomii.com/wp-content/uploads/2015/04/esp8266_pinout_h-569x236.png) 
So you should move green and yellow wires in your uno from serial pins (0 and 1) to 2nd and 3rd pin. Your second scheme doens't fit, the first scheme with leonardo was more clear about rx-tx connection for sending commands to esp8266 in regular mode.

Also don't forget to initialize your software serial in setup function:

```
void setup() {
mySerial.begin(9600); // or some other apropriate baudrate depending on firmware
...
}
```

Good luck!

**Comment by teinhonglo** [comment]
Sorry, I also cannot run it....
as below
http://i.imgur.com/zkZdEyk.jpg

my pins 3 and 2 is software rx and tx,I can't solve it...

---

(2).after I add one line
Serial.println(wifi.kick());
But output is 0, What's wrong is it?

**Comment by a-andreyev** [comment]
SoftwareSerial mySerial(3, 2), so:

> pin3 (software RX) --> esp8266 TX
> pin2 (software TX) --> esp8266 RX,

right?

As I can see, failure is present at early stage when sending esp8266 working mode.

Try to add something like this to check what stages are not passing:

```
void setupESP8266()
{
    while (1) {
        Serial.print("restaring esp8266...");
        if (esp8266.restart()) {
            Serial.print("ok\r\n");
            break;
        }
        else {
            Serial.print("not ok...\r\n");
            Serial.print("Trying to kick...");
            while (1) {
                if (esp8266.kick()) {
                    Serial.print("ok\r\n");
                    break;
                }
                else {
                    Serial.print("not ok... Wait 5 sec and retry...\r\n");
                    delay(5000);
                }
            }
        }
    }

    Serial.print("setup begin\r\n");
    Serial.print("FW Version:");
    Serial.println(esp8266.getVersion().c_str());

    while (1) {
        if (esp8266.setOprToStation()) {
            Serial.print("to station ok\r\n");
            break;
        }
        else {
            Serial.print("to station err\r\n");
            Serial.println("Wait 5 seconds and try again...");
            delay(5000);
        }
    }

    while (1) {
        if (esp8266.joinAP(SSID, PASSWORD)) {
            Serial.print("Join AP success\r\n");
            break;
        }
        else {
            Serial.print("Join AP failure\r\n");
            Serial.println("Wait 5 seconds and try again...");
            delay(5000);
        }
    }
    Serial.print("setup end\r\n");
}

void setup() {
 ... // serial setup, etc
 setupESP8266();
}
```

**Comment by teinhonglo** [comment]
but complier error esp8266 was not declare this scope?
variable esp8266 is?

my code as below..
------------------------------------------------------------------------------------
#include "ESP8266.h"
#include <SoftwareSerial.h>

#define my_SSID        "K2F01"
#define PASSWORD       "12345678"

#include <SoftwareSerial.h>
SoftwareSerial mySerial(3, 2); /* RX:D3, TX:D2 */
ESP8266 wifi(mySerial);

void setupESP8266()
{
    while (1) {
        Serial.print("restaring esp8266...");
        if (esp8266.restart()) {
            Serial.print("ok\r\n");
            break;
        }
        else {
            Serial.print("not ok...\r\n");
            Serial.print("Trying to kick...");
            while (1) {
                if (esp8266.kick()) {
                    Serial.print("ok\r\n");
                    break;
                }
                else {
                    Serial.print("not ok... Wait 5 sec and retry...\r\n");
                    delay(5000);
                }
            }
        }
    }

    Serial.print("setup begin\r\n");
    Serial.print("FW Version:");
    Serial.println(esp8266.getVersion().c_str());

    while (1) {
        if (esp8266.setOprToStation()) {
            Serial.print("to station ok\r\n");
            break;
        }
        else {
            Serial.print("to station err\r\n");
            Serial.println("Wait 5 seconds and try again...");
            delay(5000);
        }
    }

    while (1) {
        if (esp8266.joinAP(SSID, PASSWORD)) {
            Serial.print("Join AP success\r\n");
            break;
        }
        else {
            Serial.print("Join AP failure\r\n");
            Serial.println("Wait 5 seconds and try again...");
            delay(5000);
        }
    }
    Serial.print("setup end\r\n");
}

void setup() {
    // serial setup, etc
    setupESP8266();
    mySerial.begin(9600);
    Serial.begin(9600);
    Serial.print("setup begin\r\n");
    Serial.println(wifi.kick());
    Serial.print("FW Version: ");
    Serial.println(wifi.getVersion().c_str());
    
    if (wifi.setOprToStation()) {
        Serial.print("to station ok\r\n");
    } else {
        Serial.print("to station err\r\n");
    }

    if (wifi.joinAP(my_SSID, PASSWORD)) {
        Serial.print("Join AP success\r\n");
        Serial.print("IP: ");       
        Serial.println(wifi.getLocalIP().c_str());
    } else {
        Serial.print("Join AP failure\r\n");
    }
    
    Serial.print("setup end\r\n");
}

void loop(void)
{
}

**Comment by teinhonglo** [comment]
Sorry, My RX and TX is reserve, I exchange them, that is OK!(so shame...Orz)
but it output unexpected message, that is correct?
http://i.imgur.com/pjhzFYw.jpg

**Comment by a-andreyev** [comment]
Ok, not problem! I'm glad that it's more or less working at least :)

About the serial monitor results:
looks wrong, like some interference noise in the wires or something.
Not sure, it's hard to predict but looks not good for me.

**Comment by umairyounus** [comment]
Hi,

I'm getting this error:

ConnectWiFi.cpp.o: In function `__static_initialization_and_destruction_0':
/Users/umair/ConnectWiFi.ino:7: undefined reference to`ESP8266::ESP8266(SoftwareSerial&, unsigned long)'
collect2: error: ld returned 1 exit status
Error compiling.

Here is the code:

#define ESP8266_USE_SOFTWARE_SERIAL
#include "ESP8266.h"
#include <SoftwareSerial.h>

SoftwareSerial mySerial(3, 2); // RX, TX

ESP8266 wifi(mySerial);

#define SSID        "ITEAD"
#define PASSWORD    "12345678"

void setup(void)
{
    mySerial.begin(9600); // or some other apropriate baudrate depending on firmware
    Serial.begin(9600);
    Serial.print("setup begin\r\n");

```
Serial.print("FW Version: ");
Serial.println(wifi.getVersion().c_str());


if (wifi.setOprToStation()) {
    Serial.print("to station ok\r\n");
} else {
    Serial.print("to station err\r\n");
}

if (wifi.joinAP(SSID, PASSWORD)) {
    Serial.print("Join AP success\r\n");
    Serial.print("IP: ");       
    Serial.println(wifi.getLocalIP().c_str());
} else {
    Serial.print("Join AP failure\r\n");
}

Serial.print("setup end\r\n");
```

}

void loop(void)
{
}

**Comment by cszp17** [comment]
You are using a soft serial port,you should to confirm that:
1:the wiring is correct
2:open the macro in ESP8266.h ?  ->  #define ESP8266_USE_SOFTWARE_SERIAL

**Comment by inflamers** [comment]
I can't get it working, wiring is good, I switched RX & TX, on PIN 3 & 2. No error while compiling.
But it doesn't connect 
setup begin
FW Version: 
to station err
Join AP failure
setup end

Any idea ?

**Comment by DriesX** [comment]
What baudrate are you using?
I had to test a few before it worked. According to docs I found it had to be 9600 but it also didn't work. 
I'm now using 115200 and it works.

**Comment by DriesX** [comment]
I'm now using 115200 and it works.

**Comment by inflamers** [comment]
I was using 9600, I tried with each ones (including 115200) nothing works, I keep having these errors...

Here is my code 

#include <SoftwareSerial.h>
#include <doxygen.h>
#include <ESP8266.h>

SoftwareSerial mySerial(3, 2); /\* RX:D3, TX:D2 */
ESP8266 wifi(mySerial);

#define SSID        "ssid"
#define PASSWORD    "passwd"

void setup(void)
{

```
Serial.begin(115200);
Serial.print("setup begin\r\n");

Serial.print("FW Version: ");
Serial.println(wifi.getVersion().c_str());

if (wifi.setOprToStation()) {
    Serial.print("to station ok\r\n");
} else {
    Serial.print("to station err\r\n");
}

if (wifi.joinAP(SSID, PASSWORD)) {
    Serial.print("Join AP success\r\n");
    Serial.print("IP: ");       
    Serial.println(wifi.getLocalIP().c_str());
} else {
    Serial.print("Join AP failure\r\n");
}

Serial.print("setup end\r\n");
```

}

void loop(void)
{
}

**Comment by inflamers** [comment]
I also don't use any level shifter...

**Comment by DriesX** [comment]
You have to use the two serials.

Serial: console: all commands to print should be Serial.print(...)
mySerial for esp8266.

Both Serials should have the begin statement.

Serial.begin(9600); //for your print
mySerial.begin(115200); //for wifi (baudrate depends)

For the level shifter you can use three resistors in series to ground from the arduino TX and connect the ESP8266 between the first and the second resistor (from arduino TX). I've read that in the other direction from ESP8266 to Arduino it doesn't really matter. (it works in my setup)

**Comment by inflamers** [comment]
Correct, I forgot to put it back, but still no response...

#include <SoftwareSerial.h>
#include <doxygen.h>
#include <ESP8266.h>


SoftwareSerial mySerial(3, 2); /* RX:D3, TX:D2 */
ESP8266 wifi(mySerial);

#define SSID        "ssid"
#define PASSWORD    "paswd"

void setup(void)
{
    mySerial.begin(115200);
    Serial.begin(9600);
    Serial.print("setup begin\r\n");
    Serial.print("FW Version: ");
    Serial.println(wifi.getVersion().c_str());
    
    if (wifi.setOprToStation()) {
        Serial.print("to station ok\r\n");
    } else {
        Serial.print("to station err\r\n");
    }

    if (wifi.joinAP(SSID, PASSWORD)) {
        Serial.print("Join AP success\r\n");
        Serial.print("IP: ");       
        Serial.println(wifi.getLocalIP().c_str());
        
    } else {
        Serial.print("Join AP failure\r\n");
    }
    
    Serial.print("setup end\r\n");
}

**Comment by inflamers** [comment]
Correct I forgot this line,

It seems to work better than last time 

FW Version: 
to station err
Join AP success
IP: 
setup end

For some reason, I still get an "err" message, and no IP is printed, but the "Join AP success" is pretty encouraging ! Many thanks for your help !

next step is sending an email !

**Comment by inflamers** [comment]
and while running a lan scan, the device appears, so it seems to be really connected, great !

**Comment by Vigneshramkumar** [comment]
Hi,
I am trying to connect ESP8266 and Arduino UNO. I downloaded the ESP8266 library and tried the ConnectWifi program in it. But I am not able to connect to the wifi network. It is giving me the following error.
setup begin
FW Version: 
to station err
Join AP failure
setup end

PFB the program I have uploaded:
#include "ESP8266.h"
#include "SoftwareSerial.h"

SoftwareSerial mySerial(3,2);
ESP8266 wifi(mySerial);

#define SSID        "--------"
#define PASSWORD    "------------------"
//#define SERIAL_BUFFER_SIZE 256
//#define SERIAL_RX_BUFFER_SIZE 64

//ESP8266 wifi(Serial);
void setup(void)
{
    Serial.begin(9600);
    mySerial.begin(115200); 
    Serial.print("setup begin\r\n");

```
Serial.print("FW Version: ");
Serial.println(wifi.getVersion().c_str());


if (wifi.setOprToStation()) {
    Serial.print("to station ok\r\n");
} else {
    Serial.print("to station err\r\n");
}

if (wifi.joinAP(SSID, PASSWORD)) {
    Serial.print("Join AP success\r\n");
    Serial.print("IP: ");       
    Serial.println(wifi.getLocalIP().c_str());
} else {
    Serial.print("Join AP failure\r\n");
}

Serial.print("setup end\r\n");
```

}

void loop(void)
{
}
Kindly someone help me to connect the shield with the network. I already made some research with other issues section in Git hub but nothing happened.
Thanks in advance.

**Comment by agrawalnikhil** [comment]
I am using the above code 
`#include <doxygen.h>
#include <ESP8266.h>
#include <SoftwareSerial.h>
#define SSID        "SSID"
#define PASSWORD    "Password"
SoftwareSerial mySerial(3, 2); /\* RX:D3, TX:D2 */
ESP8266 wifi(mySerial);
void setupesp8266()
{
     while (1) {
        Serial.print("restaring esp8266...");
        if (esp8266.restart()) {
            Serial.print("ok\r\n");
            break;
        }
        else {
            Serial.print("not ok...\r\n");
            Serial.print("Trying to kick...");
            while (1) {
                if (esp8266.kick()) {
                    Serial.print("ok\r\n");
                    break;
                }
                else {
                    Serial.print("not ok... Wait 5 sec and retry...\r\n");
                    delay(5000);
                }
            }
        }
    }
    Serial.begin(9600);
   mySerial.begin(115200);
    Serial.print("setup begin\r\n");
  Serial.print("FW Version: ");
    Serial.println(esp8266.getVersion().c_str());
 if (esp8266.setOprToStation()) {
        Serial.print("to station ok\r\n");
        break;
    } else {
        Serial.print("to station err\r\n");
          Serial.println("Wait 5 seconds and try again...");
            delay(5000);
    }
    while(1){
    if (esp8266.joinAP(SSID, PASSWORD)) {
        Serial.print("Join AP success\r\n");
        Serial.print("IP: ");  
        Serial.println(wifi.getLocalIP().c_str());
        break;
    } else {
        Serial.print("Join AP failure\r\n");
        Serial.println("Wait 5 seconds and try again...");
            delay(5000);
    }

```
}
       Serial.print("setup end\r\n");
```

}
void setup(void)
{
  setupesp8266();
}
void loop(void)
{
}
`
but is giving following error

ConnectWiFi:12: error: 'esp8266' was not declared in this scope

```
     if (esp8266.restart()) {

         ^
```

ConnectWiFi:35: error: 'esp8266' was not declared in this scope

```
 Serial.println(esp8266.getVersion().c_str());

                ^
```

ConnectWiFi:38: error: break statement not within loop or switch

```
     break;

     ^
```

Using library ESP8266Wifi in folder: C:\Users\admin\Documents\Arduino\libraries\ESP8266Wifi (legacy)
Using library SoftwareSerial at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial 
exit status 1
'esp8266' was not declared in this scope

please help me

**Comment by alanbennett** [comment]
Can anyone help?

Arduino UNO 
genuino 1.8.1

※※※※※※※※※※※※※※※※※※※※
UNO  ->  ESP8266
----------------------------------------
3.3v    ->  3V3
3.3v   ->  EN
GND  -> GND
D2      -> TX
D3     ->  RX
※※※※※※※※※※※※※※※※※※※※


**## MY CODE ####################**
#include "ESP8266.h"
#include "SoftwareSerial.h"

#define SSID        "cgun"
#define PASSWORD    "123456789"

SoftwareSerial mySerial(3, 2); // RX,TX     uno sw RX(pin3) --> esp8266 TX, uno sw TX(pin2) --> esp8266 RX
ESP8266 wifi(mySerial);

void setup(void)
{
    Serial.begin(9600);
  mySerial.begin(115200); 

    Serial.print("setup begin\r\n");
    Serial.print("FW Version: ");
    Serial.println(wifi.getVersion().c_str());

    if (wifi.setOprToStation()) {
        Serial.print("to station ok\r\n");
    } else {
        Serial.print("to station err\r\n");
    }

    if (wifi.joinAP(SSID, PASSWORD)) {
        Serial.print("Join AP success\r\n");
        Serial.print("IP: ");       
        Serial.println(wifi.getLocalIP().c_str());
    } else {
        Serial.print("Join AP failure\r\n");
    }
    Serial.print("setup end\r\n");
}

void loop(void)
{
}
**################################**


**## RESULT ####################**
setup begin
FW Version: 
to station err
Join AP failure
setup end
**################################**

![-1](https://cloud.githubusercontent.com/assets/25955615/23213774/2cd475f6-f947-11e6-8186-86b5186012b4.jpg)

**Comment by JMAN2018** [comment]
I having a problem uploading my sketch to my attinty 85. it says serial was not declared this scope. heres my code. what do I need to d to get it to upload. I'm also not sure about the in and out pins for this. its the ldd sensor as out and light bulb as the input.


int LDR = 0;     //analog pin to which LDR is connected, here we set it to 0 so it means A0
int LDRValue = 0;      //that’s a variable to store LDR values
int light_sensitivity = 500;    //This is the approx value of light surrounding your LDR
 
void setup()
  {
    Serial.begin(9600);          //start the serial monitor with 9600 buad
    pinMode(7, OUTPUT);     //we mostly use 13 because there is already a built in yellow LED in arduino which shows output when 13 pin is enabled
  }
 
void loop()
  {
    LDRValue = analogRead(LDR);      //reads the ldr’s value through LDR 
-    Serial.println(LDRValue);       //prints the LDR values to serial monitor


}
    delay(50);        //This is the speed by which LDR sends value to arduino
 
    if (LDRValue < light_sensitivity) 
      {
        digitalWrite(7, HIGH);
      }
    else
      {
        digitalWrite(7, LOW);
      }
  }

**Comment by itxopps** [comment]
hi there 
i am new to programing. i have prepared a code for my robot. i worrks completly i compiled it many time uploaded without any problem eddited many times but suddenly it genrated an error. SERIALL1 is not decleared in this scop.i am using hc12 rf module with arduino mega 2560. code error is here.......
![sdw](https://user-images.githubusercontent.com/39178944/39905295-85284ae0-54d4-11e8-9ab6-3d52d92f2a5b.PNG)
the complete code is here.


#include <LiquidCrystal.h>

// initialize the library with the numbers of the interface pins
LiquidCrystal lcd(12, 11, 9, 8, 7, 6);
#include <Servo.h>

#include <HCPCA9685.h>
#define  I2CAdd 0x40
HCPCA9685 HCPCA9685(I2CAdd);

#define trigPin1 A5
#define echoPin1 A6

char val;// variable to receive data from the serial port

int light= 53;


int motor1Pin1 = 2; // pin 2 on L293D IC
int motor1Pin2 = 3; // pin 7 on L293D IC
int motor2Pin1 = 4; // pin 10 on L293D IC
int motor2Pin2 = 5; // pin 15 on L293D IC

int in1 = A1;
int in2 = A2;
int in3 = A3;
int in4 = A4;

int cont1 = 0;
int cont2 = 0;
int cont3 = 0;
int cont4 = 0;

// Array to store pins nos
int remotePins [] = {A1, A2, A3, A4 };

const int sensor=A0;
float tempc; 
float vout; 


int servo1 = 10; //10 to 420 
int servo2 = 200; //50 to 420
int servo3 = 420;//420
int servo4 = 150;
/
int servo5 = 220; //220  to 350

int servo6 = 420;//10 to 420

int servo7 = 200;
int servo8 = 20;//10 to 420
int servo9 = 150;

int servo10 = 250;


long duration, distance,Sensor;

void setup() 

{

  for (int i = 0; i < 5; i ++) 
  {
    pinMode (remotePins [i], INPUT);
    digitalWrite(remotePins [i], HIGH);
  }
    HCPCA9685.Init(SERVO_MODE); 
    HCPCA9685.Sleep(false); 

    pinMode(sensor,INPUT);
  
    pinMode(motor1Pin1, OUTPUT);
    pinMode(motor1Pin2, OUTPUT);
    pinMode(motor2Pin1, OUTPUT);
    pinMode(motor2Pin2, OUTPUT);

    pinMode(light, OUTPUT);

    pinMode(trigPin1, OUTPUT);
    pinMode(echoPin1, INPUT);

    // Move all Servos at start to center position
    HCPCA9685.Servo(0, servo1);  
    HCPCA9685.Servo(1, servo2); 
    HCPCA9685.Servo(2, servo2);  
    HCPCA9685.Servo(3, servo3); 
    HCPCA9685.Servo(4, servo4);
    
    HCPCA9685.Servo(5, servo5); 
    
    HCPCA9685.Servo(6, servo6); 
    HCPCA9685.Servo(7, servo7); 
    HCPCA9685.Servo(8, servo7);     
    HCPCA9685.Servo(9, servo8); 
    HCPCA9685.Servo(10, servo9);  
    
    HCPCA9685.Servo(11, 250); //250 to 400 

     
    HCPCA9685.Servo(12, servo10); 
    
    Serial1.begin(9600);
    
    Serial1.begin(9600);    
    delay(3000);

     lcd.begin(16, 2);
  // Print a message to the LCD.
  lcd.print("HIRA COLLEGE");

    lcd.setCursor(2, 1);
  lcd.print("[[[SARGODHA]]]");
  delay (3000);
  lcd.clear();
  lcd.print("HUMONOIDE ROBOT");
 
    lcd.setCursor(2, 1);
  lcd.print(",.,RF BASED,.,");
  delay (2000);
   lcd.clear();
  lcd.print("ELECTRONICS ");
 lcd.setCursor(2, 1);
    lcd.print("    DEPARTMENT ");
    delay (2000);
   lcd.clear();
  lcd.print("ELECTRONICS");
  lcd.setCursor(2, 1);
  lcd.print("     3rd YEAR ");
  delay (2000);
   lcd.clear();
     lcd.print("   FINAL YEAR "); 
    lcd.setCursor(2, 1);
    lcd.print("     PROJECT ");
     delay (2000);
   lcd.clear();
   lcd.print("  [[[ GRUOP  ]]] "); 
    lcd.setCursor(2, 1);
    lcd.print("...MEMBERS... ");
     delay (2000);
   lcd.clear();
  lcd.print("M.FAISAL G/L");
   lcd.setCursor(2, 1);
   lcd.print("ROLL NO. 51012");
  delay (4000);
   lcd.clear();
  lcd.print("ALI MANSOOR");
   lcd.setCursor(2, 1);
   lcd.print("ROLL NO. 51014");
  delay (3000);
   lcd.clear();
  lcd.print("EHTISHAM ZIA");

   lcd.setCursor(2, 1);
   lcd.print("ROLL NO. 51011");
  delay (3000);
   lcd.clear();
  lcd.print("ZARNAB HASSAN");
   lcd.setCursor(2, 1);
   lcd.print("ROLL NO. 51001");
  delay (3000);
   lcd.clear();
   lcd.print("SUPERVISOR ENGR.");
   lcd.setCursor(2, 1);
   lcd.print("SHOAIB AKHTAR");
  delay (3000);
   lcd.clear();
  lcd.print("    SESSION ");
  lcd.setCursor(2, 1);
  lcd.print("  2015 - 2018 ");
  delay (2000);
   lcd.clear();
  lcd.print("FYP  2018");
   lcd.setCursor(2, 1);
  lcd.print("HIRA COLLEGE  ");
  delay (2000);
   lcd.clear();
  lcd.print(" RF Based Self");
   lcd.setCursor(2, 1);
  lcd.print("Defence Robot");
  delay (2000);

}



void loop() 
{  
   lcd.setCursor(0, 0);
 
  lcd.display();
  delay(3000);
//if( Serial.available()>0) // if data is available to read
//{
//val = Serial.read(); // read it and store it in 'val'
//}

if( Serial1.available()>0) // if data is available to read
{
val = Serial1.read(); // read it and store it in 'val'
}
SonarSensor(trigPin1, echoPin1);
Sensor = distance; 
//Serial.println(Sensor); 
 
if( val == '1' )
{
if(Sensor>60)
{   
digitalWrite(motor1Pin1, LOW);digitalWrite(motor1Pin2, HIGH); digitalWrite(motor2Pin1, LOW);digitalWrite(motor2Pin2, HIGH);  
}
if(Sensor<60)
{  
 digitalWrite(motor1Pin1, LOW);digitalWrite(motor1Pin2, LOW); digitalWrite(motor2Pin1, LOW);digitalWrite(motor2Pin2, LOW);  
  }
}
if( val == '2' )
{ 
if(Sensor>60)
{     
digitalWrite(motor1Pin1, HIGH);digitalWrite(motor1Pin2, LOW); digitalWrite(motor2Pin1, HIGH);digitalWrite(motor2Pin2, LOW);  
}
if(Sensor<60)
{ 
 digitalWrite(motor1Pin1, LOW);digitalWrite(motor1Pin2, LOW); digitalWrite(motor2Pin1, LOW);digitalWrite(motor2Pin2, LOW);  
  } 
 }
if( val == '4' )
{ 
digitalWrite(motor1Pin1, HIGH);digitalWrite(motor1Pin2, LOW); digitalWrite(motor2Pin1, LOW);digitalWrite(motor2Pin2, HIGH);  
 }
if( val == '3' )
{
if(Sensor>60)
{     
if (digitalRead (in1) == LOW) 
 {  
digitalWrite(motor1Pin1, LOW);digitalWrite(motor1Pin2, HIGH); digitalWrite(motor2Pin1, HIGH);digitalWrite(motor2Pin2, LOW);
 }
if (digitalRead (in1) == HIGH) 
 {
 digitalWrite(motor1Pin1, LOW);digitalWrite(motor1Pin2, LOW); digitalWrite(motor2Pin1, LOW);digitalWrite(motor2Pin2, LOW);   
 delay(500);
digitalWrite(motor1Pin1, HIGH);digitalWrite(motor1Pin2, LOW); digitalWrite(motor2Pin1, LOW);digitalWrite(motor2Pin2, HIGH);   
 delay(500);
  digitalWrite(motor1Pin1, LOW);digitalWrite(motor1Pin2, LOW); digitalWrite(motor2Pin1, LOW);digitalWrite(motor2Pin2, LOW);   
 delay(500);
 val = '0';
 }
}
if(Sensor<60)
{ 
 digitalWrite(motor1Pin1, LOW);digitalWrite(motor1Pin2, LOW); digitalWrite(motor2Pin1, LOW);digitalWrite(motor2Pin2, LOW);  
 } 
 
 
}

if( val == '5' )
{
digitalWrite(motor1Pin1, LOW);digitalWrite(motor1Pin2, LOW); digitalWrite(motor2Pin1, LOW);digitalWrite(motor2Pin2, LOW);
}

if( val == 'S' )

{ 
  servo1 = 10;  
  servo2 = 200; 
  servo3 = 420;
  servo4 = 250;
  servo5 = 220; 
  servo6 = 420;
  servo7 = 220;
  servo8 = 20;
  servo9 = 250;
  servo10 = 250;
  
    HCPCA9685.Servo(0, servo1);  
    HCPCA9685.Servo(1, servo2); 
    HCPCA9685.Servo(2, servo2);  
    HCPCA9685.Servo(3, servo3); 
    HCPCA9685.Servo(4, servo4);
    HCPCA9685.Servo(5, servo5); 
    HCPCA9685.Servo(6, servo6); 
    HCPCA9685.Servo(7, servo7); 
    HCPCA9685.Servo(8, servo7);     
    HCPCA9685.Servo(9, servo8); 
    HCPCA9685.Servo(10, servo9);  
    HCPCA9685.Servo(11, 250); //250 to 400 
    HCPCA9685.Servo(12, servo10);   
}

if( val == 'K' )
{if(servo2<420){servo2 = servo2+4;HCPCA9685.Servo(1, servo2);HCPCA9685.Servo(2, servo2);delay(20);}}
if( val == 'k' )
{if(servo2>50){servo2 = servo2-4;HCPCA9685.Servo(1, servo2);HCPCA9685.Servo(2, servo2);delay(20);}}

if( val == 'C' )
{if(servo7<420){servo7 = servo7+4;HCPCA9685.Servo(7, servo7);HCPCA9685.Servo(8, servo7);delay(20);}}
if( val == 'c' )
{if(servo7>50){servo7 = servo7-4;HCPCA9685.Servo(7, servo7);HCPCA9685.Servo(8, servo7);delay(20);}}


if( val == 'B' )
{if(servo6<420){servo6 = servo6+4;HCPCA9685.Servo(6, servo6);delay(20);}}
if( val == 'b' )
{if(servo6>80){servo6 = servo6-4;HCPCA9685.Servo(6, servo6);delay(20);}}

if( val == 'I' )
{if(servo3<420){servo3 = servo3+4;HCPCA9685.Servo(3, servo3);delay(20);}}
if( val == 'i' )
{if(servo3>10){servo3 = servo3-4;HCPCA9685.Servo(3, servo3);delay(20);}}

if( val == 'N' )
{if(servo4<420){servo4 = servo4+4;HCPCA9685.Servo(4, servo4);delay(20);}}
if( val == 'n' )
{if(servo4>10){servo4 = servo4-4;HCPCA9685.Servo(4, servo4);delay(20);}}

if( val == 'D' )
{if(servo8<420){servo8 = servo8+4;HCPCA9685.Servo(9, servo8);delay(20);}}
if( val == 'd' )
{if(servo8>10){servo8 = servo8-4;HCPCA9685.Servo(9, servo8);delay(20);}}


if( val == 'M' )
{if(servo9<420){servo9 = servo9+4;HCPCA9685.Servo(10, servo9);delay(20);}}
if( val == 'm' )
{if(servo9>10){servo9 = servo9-4;HCPCA9685.Servo(10, servo9);delay(20);}}

if( val == 'G' )
{if(servo1<350){servo1 = servo1+4;HCPCA9685.Servo(0, servo1);delay(20);}}
if( val == 'g' )
{if(servo1>10){servo1 = servo1-4;HCPCA9685.Servo(0, servo1);delay(20);}}

if( val == 'h' )
{if(servo5<350){servo5 = servo5+4;HCPCA9685.Servo(5, servo5);delay(20);}}
if( val == 'H' )
{if(servo5>220){servo5 = servo5-4;HCPCA9685.Servo(5, servo5);delay(20);}}


if( val == 'J' )
{if(servo10<420){servo10 = servo10+4;HCPCA9685.Servo(12, servo10);delay(20);}}
if( val == 'j' )
{if(servo10>10){servo10 = servo10-4;HCPCA9685.Servo(12, servo10);delay(20);}}

if( val == 'F' )
{HCPCA9685.Servo(11, 410); delay(1000); HCPCA9685.Servo(11, 250); val = '0';}


if( val == 'Z' )
{lightON();}
if( val == 'z' )
{lightOFF();}

vout=analogRead(sensor);
vout=(vout*500)/1023;
tempc=vout;

if (digitalRead (in4) == HIGH) 
 {
if(cont1==0)
{ 
Serial1.println("A");  
cont1 = 1;  
delay(100); 
}  
}
else{
if(cont1==1)
 { 
Serial1.println("a");  
cont1 = 0;  
delay(100); 
 }
 }

if (digitalRead (in3) == LOW) 
 {
if(cont2==0)
{ 
Serial1.println("B");  
cont2 = 1;  
delay(100); 
}  
}
else{
if(cont2==1)
 { 
Serial1.println("b");  
cont2 = 0;  
delay(100); 
 }
 }

 if (tempc>50) 
 {
if(cont3==0)
{ 
Serial1.println("C");  
cont3 = 1;  
delay(100); 
}  
}
else{
if(cont3==1)
 { 
Serial1.println("c");  
cont3 = 0;  
delay(100); 
 }
 }

 if (digitalRead (in2) == LOW) 
 {
if(cont4==0)
{ 
Serial1.println("D");  
cont4 = 1;  
delay(100); 
}  
}
else{
if(cont4==1)
 { 
Serial1.println("d");  
cont4 = 0;  
delay(100); 
 }
 }

//Serial.print("in DegreeC=");
//Serial.print("\t");
//Serial.println(tempc);
 
}

void lightON(){digitalWrite(light, HIGH);}
void lightOFF(){digitalWrite(light, LOW);}

void SonarSensor(int trigPin,int echoPin)
{
digitalWrite(trigPin, LOW);
delayMicroseconds(2);
digitalWrite(trigPin, HIGH);
delayMicroseconds(10);
digitalWrite(trigPin, LOW);
duration = pulseIn(echoPin, HIGH);
distance = (duration/2) / 29.1;

}
