### ISSUE TITLE
Large Buffer

### ISSUE THREAD

**Issue by gary9716** [itead/ITEADLIB_Arduino_WeeESP8266#42]
The example in /examples/HTTPGET cannot work on UNO.
It always failed to establish a tcp connection.
After I change the buffer size in line 65 from 1024 to 128, it worked smoothly.
So I wondered this is an issue or not?

**Comment by Stavr0s13** [comment]
It works with 256 too,
Also worked with 374(largest i get to work) but for some reason it fails to createTCP but gets the request.
But i always i get failed to release TCP even with 20 sec delay, dunno why

**Comment by cszp17** [comment]
yes,you are right.because if the buffer size is 1024.In the process of program is running, the memory will be less than
