### ISSUE TITLE
Problem on sending binary data

### ISSUE THREAD

**Issue by tgober** [itead/ITEADLIB_Arduino_WeeESP8266#5]
when sending the char '\0' (normal thing on transfering binary data), the "wait for 'SEND OK'" will fail.

**Comment by muesliman** [comment]
diff --git a/ESP8266.cpp b/ESP8266.cpp
index c03b56c..1fae775 100644
--- a/ESP8266.cpp
+++ b/ESP8266.cpp
@@ -381,6 +381,7 @@ String ESP8266::recvString(String target, uint32_t timeout)
     while (millis() - start < timeout) {
         while(m_puart->available() > 0) {
             a = m_puart->read();
+			if(a == '\0') continue;
             data += a;
         }
         if (data.indexOf(target) != -1) {
@@ -398,6 +399,7 @@ String ESP8266::recvString(String target1, String target2, uint32_t timeout)
     while (millis() - start < timeout) {
         while(m_puart->available() > 0) {
             a = m_puart->read();
+			if(a == '\0') continue;
             data += a;
         }
         if (data.indexOf(target1) != -1) {
@@ -417,6 +419,7 @@ String ESP8266::recvString(String target1, String target2, String target3, uint3
     while (millis() - start < timeout) {
         while(m_puart->available() > 0) {
             a = m_puart->read();
+			if(a == '\0') continue;
             data += a;
         }
         if (data.indexOf(target1) != -1) {
